"""add category fields

Revision ID: 84d7a53b7b7d
Revises: 651b529cfe59
Create Date: 2026-04-28 11:48:53.971930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d7a53b7b7d'
down_revision: Union[str, Sequence[str], None] = '651b529cfe59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('category', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('sub_category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'sub_category')
    op.drop_column('tasks', 'category')
    # ### end Alembic commands ###
