"""enum update

Revision ID: 94fc386f22bd
Revises: fce1951d03ea
Create Date: 2026-04-28 10:04:25.291647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94fc386f22bd'
down_revision: Union[str, Sequence[str], None] = 'fce1951d03ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('estimate_time', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('completed_time', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'created_at')
    op.drop_column('tasks', 'due_date')
    op.drop_column('tasks', 'completed_time')
    op.drop_column('tasks', 'estimate_time')
    # ### end Alembic commands ###
